"""update comment table

Revision ID: e30b39a7c558
Revises: c10b0a667156
Create Date: 2020-08-13 14:26:34.368792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30b39a7c558'
down_revision = 'c10b0a667156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('path', sa.Text(), nullable=True))
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comment_path'), 'comment', ['path'], unique=False)
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_path'), table_name='comment')
    op.drop_column('comment', 'post_id')
    op.drop_column('comment', 'path')
    op.drop_column('comment', 'parent_id')
    # ### end Alembic commands ###
